development:
  adapter: postgresql
  encoding: unicode
  database: spawexpert_development
  pool: 5
  username: postgres
  password: Kopalnia1


test:
  adapter: postgresql
  encoding: unicode
  database: spawexpert_test
  pool: 5
  username: postgres
  password: Kopalnia1



production:
  adapter: postgresql
  encoding: unicode
  database: spawexpert_production
  pool: 5
  username: postgres
  password: Kopalnia1